#!/usr/bin/env node
/**
 * Workflow automation CLI (Level 3, Project 1).
 * Automates: pre-flight → tests → build → create PR, with gates that
 * stop the pipeline on failure. Gate logic lives in ./gates.js so it's
 * unit-testable (Project 3).
 *
 * Run: node index.js [--dry-run]
 * `--dry-run` simulates each step without touching git.
 */
const fs = require('fs');
const { execSync } = require('child_process');
const { runWorkflow } = require('./gates');

const DRY = process.argv.includes('--dry-run');

function run(label, cmd) {
  console.log(`\n▶ ${label}`);
  if (DRY) return { ok: true, output: '' };
  try {
    const output = execSync(cmd, { stdio: ['pipe', 'pipe', 'pipe'] }).toString();
    console.log(`  ${output.split('\n').filter(Boolean).slice(0, 3).join('\n  ') || 'ok'}`);
    return { ok: true, output };
  } catch (e) {
    const err = (e.stderr ? e.stderr.toString() : e.message).trim();
    console.error(`  FAILED: ${err.split('\n')[0]}`);
    return { ok: false, output: err };
  }
}

function gatherContext() {
  if (DRY) {
    return { dryRun: true, branch: 'main', uncommitted: false, testsPass: true, buildPass: true };
  }
  let branch = '';
  try {
    branch = execSync('git branch --show-current').toString().trim();
  } catch {}
  let uncommitted = false;
  try {
    uncommitted = execSync('git status --porcelain').toString().trim().length > 0;
  } catch {}
  let testsPass = true;
  try {
    execSync('npm test -- --silent', { stdio: 'ignore' });
  } catch {
    testsPass = false;
  }
  let buildPass = true;
  try {
    execSync('npm run build', { stdio: 'ignore' });
  } catch {
    buildPass = false;
  }
  return { dryRun: false, branch, uncommitted, testsPass, buildPass };
}

console.log('=== Workflow: feature → test → build → PR ===\n');

const result = runWorkflow(gatherContext());

if (!result.ok) {
  console.error(`\n🔴 Blocked by ${result.blockedBy}: ${result.detail}`);
  process.exit(1);
}

console.log(`\n✅ ${result.detail}`);

// PR step only reached if all gates passed.
const pr = run('create PR', 'gh pr create --title "chore: automated workflow" --body "Generated by workflow automation" 2>/dev/null || echo "no gh / dry"');

const report = [
  '# Workflow Execution Report',
  '',
  `- Gates: ${result.detail}`,
  `- PR: ${pr.ok ? '✅ opened' : '— skipped (no gh)'}`,
  `- Mode: ${DRY ? 'dry-run' : 'real'}`,
  '',
].join('\n');
fs.writeFileSync('workflow-report.md', report);
console.log(`\n📄 Report written to workflow-report.md`);
